name: Android

on: [push, pull_request]

jobs:
  build_and_test:
    environment: android
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install git-crypt
        run: sudo apt install -y git-crypt gnupg2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}.keys[0]
          passphrase: ${{ secrets.SIGNING_GNUPG_PASSWORD }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}
          gpg-passphrase: ${{ secrets.SIGNING_GNUPG_PASSWORD }}
      - name: Build task gradle sign
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: sign
        env:
          GPG_KEY_ID: ${{ secrets.SIGNING_GNUPG_KEYID}}
          GPG_PRIVATE_KEY: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}
          GPG_PASSPHRASE: ${{ secrets.SIGNING_GNUPG_PASSWORD }}
      - name: Publish to Nexus repository
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_GNUPG_PASSWORD }}